### PR TITLE
fixes counter not incrementing

### LINKED ISSUE #168: Counter no longer increments
**Describe the bug**
Counter no longer increments after https://github.com/euzu/m3u-filter/commit/c4b336c0ea244828d11870fa274c5a206ca928b2

**To Reproduce**
1. Setup a mapping with a counter
2. Run with current version

**Expected behavior**
Counter should increment

**Additional context**
I pulled tag [v2.0.6](https://github.com/euzu/m3u-filter/tree/v2.0.6) and the counter incremented as expected.
Pulling and building v2.0.7 results in no counter increment.

I think it's simply assigning the value of counter to `cntval` outside the for loop is the issue. As this change has it working correctly.

Image

### PR DESCRIPTION
**Pull request by denniswebb**
closes #168

### CODE REVIEW

File: src/processing/playlist_processor.rs [hunk 1]
```diff
@@ -593,4 +593,4 @@ pub async fn exec_processing(client: Arc<reqwest::Client>, cfg: Arc<Config>, tar
     }
     let elapsed = start_time.elapsed().as_secs();
     info!("Update process finished! Took {elapsed} secs.");
-}
\ No newline at end of file
+}
```
Comment (denniswebb) [inline src/processing/playlist_processor.rs:596]:
```suggestion
}

```

File: src/processing/playlist_processor.rs [hunk 2]
```diff
@@ -593,4 +593,5 @@ pub async fn exec_processing(client: Arc<reqwest::Client>, cfg: Arc<Config>, tar
...
+
```
Comment (denniswebb) [inline src/processing/playlist_processor.rs:597]:
```suggestion
}
```
